language: c

sudo: false

env:
  global:
    - RACKET_DIR: '~/racket'
  matrix:
    - RACKET_VERSION: 6.2
    - RACKET_VERSION: 6.2.1
    - RACKET_VERSION: 6.3
    - RACKET_VERSION: HEAD

before_install:
  - git clone https://github.com/greghendershott/travis-racket.git
  - cat travis-racket/install-racket.sh | bash
  - export PATH="${RACKET_DIR}/bin:${PATH}"

install:
  - raco pkg install --auto --name collections-lens --link $TRAVIS_BUILD_DIR
  - if [ "$RACKET_VERSION" == 'HEAD' ]; then raco pkg install --auto cover cover-coveralls; fi

script:
  - raco test -ep collections-lens
  - if [ "$RACKET_VERSION" == 'HEAD' ]; then raco cover -bf coveralls -d $TRAVIS_BUILD_DIR/coverage -p collections-lens; fi
